### ISSUE TITLE
UI improvement needed

### ISSUE THREAD

**Issue by darshanr27** [darshanr27/top-indian-singers-blog#4]
## TO-DO
- [x] Change the color of the navbar to a good one.
- [x] Color of the titles in the blog pages needs changes.
- [x] Font color in the blog page needs changes ( Fonts in the individuals' details page, not on index page). 

### Don't touch
- The font style.
- The font color on the index page.
- Background color.
- Contents

*You can discuss here for any clarifications. Before starting work, clear all the doubts. Comment if you want to work on this, then I will assign it to you.*

**Comment by SouvickMazumdar** [comment]
hello, 
Please assign me this issue

**Comment by darshanr27** [comment]
@SouvickMazumdar Hello.
Assigned...! Start working on it, please do follow the points mentioned above.

**Comment by SouvickMazumdar** [comment]
ok

**Comment by darshanr27** [comment]
@SouvickMazumdar I'm going to close all the individual commit PR's #5 , #6 , and #7 , now you can rework on it and do all the changes once, then commit and then make one PR for all the commits once.

**Comment by darshanr27** [comment]
> sorry for some misunderstanding. In The latest pull request i have made all the necessary changes.

Ok, I will look into it.

**Comment by darshanr27** [comment]
Okay, everything is good but you messed up with the blog content font color, just reverted back to the previous code.
